[package]
name = "async-await-echo"
version = "0.1.0"
authors = ["GuillaumeClementPolytech <guillaume.clement@etu.umontpellier.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
