[package]
name = "meow"
version = "0.1.0"
authors = ["GuillaumeClementPolytech <guillaume.clement@etu.umontpellier.fr>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
dotenv_codegen = "0.14.1"
